"""added Env model

Revision ID: 7394fff372d2
Revises: cf3f7b8ffee7
Create Date: 2020-03-24 15:00:23.228354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7394fff372d2'
down_revision = 'cf3f7b8ffee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('env',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('parent_audit', 'a_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_audit', sa.Column('a_user', sa.VARCHAR(length=64), nullable=True))
    op.drop_table('env')
    # ### end Alembic commands ###
