"""add a_user column

Revision ID: 82cef3086e61
Revises: 436be577127c
Create Date: 2020-03-07 10:23:09.170982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82cef3086e61'
down_revision = '436be577127c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_audit', sa.Column('a_user', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parent_audit', 'a_user')
    # ### end Alembic commands ###
