"""add description column to App and Env

Revision ID: a3e207f3145a
Revises: 7394fff372d2
Create Date: 2020-03-24 21:14:49.042674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e207f3145a'
down_revision = '7394fff372d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('desc', sa.String(length=128), nullable=True))
    op.add_column('env', sa.Column('desc', sa.String(length=128), nullable=True))
    op.drop_column('parent_audit', 'a_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_audit', sa.Column('a_user', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('env', 'desc')
    op.drop_column('app', 'desc')
    # ### end Alembic commands ###
