"""added app and appaudit tables

Revision ID: cf3f7b8ffee7
Revises: ec6dc5e5d53a
Create Date: 2020-03-22 09:30:26.580528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf3f7b8ffee7'
down_revision = 'ec6dc5e5d53a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('a_datetime', sa.DateTime(), nullable=True),
    sa.Column('a_user_id', sa.Integer(), nullable=True),
    sa.Column('a_username', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.Column('before', sa.String(), nullable=True),
    sa.Column('after', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['app.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('parent_audit', 'a_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_audit', sa.Column('a_user', sa.VARCHAR(length=64), nullable=True))
    op.drop_table('app_audit')
    op.drop_table('app')
    # ### end Alembic commands ###
