"""added a_username to the audit schema

Revision ID: ec6dc5e5d53a
Revises: 259540b5357e
Create Date: 2020-03-20 08:06:51.951471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec6dc5e5d53a'
down_revision = '259540b5357e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_audit', sa.Column('a_user_id', sa.Integer(), nullable=True))
    op.add_column('parent_audit', sa.Column('a_username', sa.String(length=64), nullable=True))
    op.drop_column('parent_audit', 'a_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_audit', sa.Column('a_user', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('parent_audit', 'a_username')
    op.drop_column('parent_audit', 'a_user_id')
    # ### end Alembic commands ###
