"""removed AppAudit model

Revision ID: fb775a0d0083
Revises: a3e207f3145a
Create Date: 2020-03-24 21:39:27.378427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb775a0d0083'
down_revision = 'a3e207f3145a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_audit')
    op.drop_column('parent_audit', 'a_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_audit', sa.Column('a_user', sa.VARCHAR(length=64), nullable=True))
    op.create_table('app_audit',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('a_datetime', sa.DATETIME(), nullable=True),
    sa.Column('a_user_id', sa.INTEGER(), nullable=True),
    sa.Column('a_username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('action', sa.VARCHAR(length=64), nullable=True),
    sa.Column('before', sa.VARCHAR(), nullable=True),
    sa.Column('after', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['app.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
